- name: Load target-specific EVA Agent Workspace values
  ansible.builtin.import_tasks: workspace_values.yaml

- name: Install Agent Dependencies
  ansible.builtin.import_tasks: dependencies.yaml

- name: Install Agent
  ansible.builtin.import_tasks: agent.yaml
